### ISSUE TITLE
System crashes with oops message requiring logout with Astra Monitor the instigator

### ISSUE THREAD

**Issue by KeithMyers** [AstraExt/astra-monitor#179]
## Steps to Reproduce

1.
2.
3. 

## Environment

-   **Astra Monitor Version**:
-   **GNOME Version**:
-   **Operating System and Version**:
-   **Other Relevant System Information**:

**Comment by KeithMyers** [comment]
No steps necessary, just use system for a while.  Browser being used along with normal applications running.

Astra Monitor version 32 (EGOv49)
Gnome version 46 X11 window manager
Ubuntu 24.04.2 LTS
kernel 6.13.2-061302-generic

Cascading failure starts with this entry in the journal
`Feb 21 10:33:04 Serenity gnome-shell[30132]: Error: Failed to initialize subprocess: Too many open files
                                             runCommand/<@file:///home/keith/.local/share/gnome-shell/extensions/monitor@astraext.g>
                                             runCommand@file:///home/keith/.local/share/gnome-shell/extensions/monitor@astraext.git>
                                             listDisksAsync@file:///home/keith/.local/share/gnome-shell/extensions/monitor@astraext>
                                             updateStorageUsageProc@file:///home/keith/.local/share/gnome-shell/extensions/monitor@>
                                             updateStorageUsageAuto@file:///home/keith/.local/share/gnome-shell/extensions/monitor@>
                                             makeCancellable/promise</timeoutId<@file:///home/keith/.local/share/gnome-shell/extens>
                                             @resource:///org/gnome/shell/ui/init.js:21:20
                                                Astra Monitor ERROR: Error getting disk list`

Then this entry is repeated for several pages until

`Feb 21 10:36:04 Serenity gnome-shell[30132]: epoll_create1 () failed: Too many open files
Feb 21 10:36:04 Serenity gnome-shell[30132]: GNOME Shell crashed with signal 5
Feb 21 10:36:04 Serenity gnome-shell[30132]: == Stack trace for context 0x613c512fc6c0 ==
Feb 21 10:36:04 Serenity gnome-shell[30132]: #0   613c513c8be8 i   resource:///org/gnome/shell/ui/init.js:21 (23fa54e70bf0 @ 48)
Feb 21 10:36:05 Serenity systemd[3348]: Starting update-notifier-crash.service - Notification regarding a crash report...
Feb 21 10:36:05 Serenity update-notifier-crash[52504]: /usr/bin/whoopsie
Feb 21 10:36:05 Serenity systemd[3348]: Finished update-notifier-crash.service - Notification regarding a crash report.
Feb 21 10:36:13 Serenity systemd[3348]: Starting update-notifier-crash.service - Notification regarding a crash report...
Feb 21 10:36:13 Serenity update-notifier-crash[52609]: /usr/bin/whoopsie
Feb 21 10:36:13 Serenity polkitd[1801]: Unregistered Authentication Agent for unix-session:77 (system bus name :1.230, object path >
Feb 21 10:36:13 Serenity systemd[3348]: org.gnome.Shell@x11.service: Main process exited, code=dumped, status=5/TRAP
Feb 21 10:36:13 Serenity update-notifier-crash[52611]: gnome-shell
Feb 21 10:36:14 Serenity systemd[3348]: org.gnome.Shell@x11.service: Failed with result 'core-dump'.
Feb 21 10:36:14 Serenity systemd[3348]: org.gnome.Shell@x11.service: Triggering OnFailure= dependencies.
Feb 21 10:36:14 Serenity systemd[3348]: org.gnome.Shell@x11.service: Consumed 21min 31.455s CPU time.
Feb 21 10:36:14 Serenity systemd[3348]: org.gnome.Shell@x11.service: Scheduled restart job, restart counter is at 1.
Feb 21 10:36:14 Serenity systemd[3348]: Started gnome-session-failed.service - GNOME Session Failed lockdown screen (user).
Feb 21 10:36:14 Serenity systemd[3348]: Reached target gnome-session-failed.target - GNOME Session Failed.
Feb 21 10:36:14 Serenity systemd[3348]: org.gnome.Shell-disable-extensions.service - Disable GNOME Shell extensions after failure w>
Feb 21 10:36:14 Serenity systemd[3348]: Starting org.gnome.Shell@x11.service - GNOME Shell on X11...
Feb 21 10:36:14 Serenity gnome-shell[52641]: Running GNOME Shell (using mutter 46.2) as a X11 window and compositing manager
`

Then all gpus start dumping into the logs.  End result is a "Oops" white screen saying the desktop need to be restarted by logging out and logging back in.

This had occurred at least once every day now for the past couple of days.  Coincidentally, I have been advised upon reboot to desktop that a Gnome extension needs be updated by logging out. The extension needing to be updated is Astra Monitor.  I have done this for the past several days.  I don't know what changes to the extension have been but suspect that the changes are what is causing this crash in the Gnome desktop.  

Astra Monitor has been error free up until I have been presented with this advisory to update the extension.

**Comment by KeithMyers** [comment]
Having the exact same issue on all my hosts.  Two other 9950 rigs configured 99% the same as this daily driver.
Also having the issues on my two Epyc servers.  A 7713 and a 7B13.

Crashes the desktop when Astra Monitor starts throwing the "too many open files" error.

**Comment by KeithMyers** [comment]
Trying an experiment where I un-monitor both Storage and Network to see if that resolves the issue.

**Comment by ljuzig** [comment]
This was a known issue on the previous version (see #176) but the log above can't be from the latest release. Probably it got updated right after the crash. Make sure you have Experimenta Features disabled in Settings > Utility. Let me know if you encounter this bug with the latest version with an updated log. Thank you!

![Image](https://github.com/user-attachments/assets/3004ccad-2106-4c0b-8a61-032ec4e2c2cf)

**Comment by KeithMyers** [comment]
I'm pretty sure I was already on the latest release 32 BEFORE the latest crash.  On ALL my hosts.  The desktop was freezing on all the hosts until I untoggled the Storage and Network monitors.

Also, I don't run any of the environments or programs mentioned in [https://github.com/AstraExt/astra-monitor/issues/176](https://github.com/AstraExt/astra-monitor/issues/176)

I run BOINC on all the hosts which stresses all systems to a great extent.

**Comment by ljuzig** [comment]
Yes, I just realized I was wrong, enabling the experimental feature should temporarily fix the issue. I'm gonna release a fix very shortly anyway.

**Comment by ljuzig** [comment]
I issued a new release, v33. Let me know if you face this bug again. Thank you.

**Comment by KeithMyers** [comment]
Puzzled with your reply. You need to toggle the experimental features which I HAVE NOT ever toggled before to fix the issue?

Or, the issue is resolved with the new version 33?

**Comment by ljuzig** [comment]
The issue _should_ be fixed in v33. Since it's not accepted yet by gnome extensions you can enable that toggle which uses a different algorithm to spawn subprocesses which _should_ be bug free. Hope I've been more clear now!

**Comment by KeithMyers** [comment]
OK, I understand.  I tried to get the new version thru gnome extensions but kept getting the current v32.  I'll try the experimental options on this daily driver since this one is critical for not crashing.  The other hosts just do BOINC so don't have to normally ever have the GNOME DE in play since nobody is sitting in front of them using the desktop.

**Comment by KeithMyers** [comment]
Well, unfortunately, v32 with experimental posix spawning subprocess option in use didn't prevent the desktop from still crashing on me must now.

`Feb 21 19:22:15 Serenity gjs[147029]: Error
                                      warn@file:///home/keith/.local/share/gnome-shell/extensions/monitor@astraext.github.io/src/ut>
                                      getGPUsList@file:///home/keith/.local/share/gnome-shell/extensions/monitor@astraext.github.io>
                                      hasAMDGpu@file:///home/keith/.local/share/gnome-shell/extensions/monitor@astraext.github.io/s>
                                      getWelcomePage@file:///home/keith/.local/share/gnome-shell/extensions/monitor@astraext.github>
                                      setupWelcome@file:///home/keith/.local/share/gnome-shell/extensions/monitor@astraext.github.i>
                                      Welcome@file:///home/keith/.local/share/gnome-shell/extensions/monitor@astraext.github.io/src>
                                      fillPreferencesWindow@file:///home/keith/.local/share/gnome-shell/extensions/monitor@astraext>
                                      _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:41:18
                                      async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:26:14
                                      ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:17:4
                                      OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
                                      async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
                                      _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
                                      _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/G>
                                         Astra Monitor WARNING: Error getting GPUs list:         Subsystem: eVga.com. Corp. GA102 H>
`

**Comment by KeithMyers** [comment]
And just crashed again instantly after logging out and back in and accessing the Astra Monitor gear icon.
