### ISSUE TITLE
RAM usage increases each time Astra Monitor is re-enabled

### ISSUE THREAD

**Issue by G-dH** [AstraExt/astra-monitor#181]
## Description

With every screen unlocking Astra Monitor consumes another ~30 MB of RAM
 
## Steps to Reproduce

1. Enable Astra Monitor
2. Check the size of `gnome-shell` process
3. Lock the screen
4. Unlock the screen
5. Observe the increase in the size of `gnome-shell` process

## Environment

-   **Astra Monitor Version**: 33/50
-   **GNOME Version**: 46.0
-   **Operating System and Version**: Ubuntu 24.04.2
-   **Other Relevant System Information**: Intel® UHD Graphics 620

## Logs

Nothing relevant

## Additional Context

Tested with all other extensions disabled and the Gnome session restarted.

[gsettings-dump.txt](https://github.com/user-attachments/files/18985498/gsettings-dump.txt)

**Comment by ljuzig** [comment]
I'm working on this issue. I've traced it back to the v20 update, but it might take a while because I want to rework several things to prevent this from happening again in the future.

**Comment by samoverton** [comment]
Do you know if there's a specific feature or option which causes it and can be worked around?

This issue is currently preventing me from using Astra Monitor.

**Comment by ljuzig** [comment]
This build should fix the issue. I'll take some time before releasing it to conduct more thorough testing.

[monitor@astraext.github.io.shell-extension.zip](https://github.com/user-attachments/files/19412306/monitor%40astraext.github.io.shell-extension.zip)

**Comment by G-dH** [comment]
I hate to say this, but the problem is still there even in version 34. Only the leak is smaller.
